A couple of yq fixups
linkerd/website pull request #1018
Opened 2021-03-31 14:30 UTC by alpeb

Fixes linkerd/linkerd2#5801

2021-03-31 15:54 UTC, kleimkuhler approved these changes

2021-04-05 16:51 UTC, lagalbra requested changes

2021-04-05 16:51 UTC, lagalbra commented on linkerd.io/content/2.10/tasks/manually-rotating-control-plane-tls-credentials.md
> -# For Linkerd < 2.9.0:
Why remove the Linkerd < 2.9.0 steps for one doc and not the other? Is Linkerd 2.9.0 the oldest supported version?

2021-04-05 16:51 UTC, lagalbra commented on linkerd.io/content/2.10/tasks/manually-rotating-control-plane-tls-credentials.md
> +  | yq -r .identityTrustAnchorsPEM - > original-trust.crt
As noted in https://github.com/linkerd/linkerd2/issues/5801, and changed in #989 , this syntax does not work with yq version 0.4.5

2021-04-05 17:28 UTC, alpeb commented on linkerd.io/content/2.10/tasks/manually-rotating-control-plane-tls-credentials.md
> -# For Linkerd < 2.9.0:
Only as of the release of version `2.10` we started keeping versioned docs. So for versions `2.9` and earlier you should go to https://linkerd.io/2.9/overview/ and for `2.10` the docs are at https://linkerd.io/2.10/overview/
So given there are separate docs for `2.9`, we're not keeping `2.9`-only info in the `2.10` docs.

2021-04-05 17:31 UTC, alpeb commented on linkerd.io/content/2.10/tasks/manually-rotating-control-plane-tls-credentials.md
> +  | yq -r .identityTrustAnchorsPEM - > original-trust.crt
I'm testing with the `yq` utility from [this repo](https://github.com/kislyuk/yq), whose latest version is `2.12.0`. Can you please point me to what `yq` you're referring to?

2021-04-05 17:59 UTC, lagalbra commented on linkerd.io/content/2.10/tasks/manually-rotating-control-plane-tls-credentials.md
> +  | yq -r .identityTrustAnchorsPEM - > original-trust.crt
I am using version 4.5.0 from [this repo](https://github.com/mikefarah/yq), as that tool (not that particular version though) is referenced in other linkerd docs such as https://linkerd.io/2.10/tasks/installing-multicluster/

2021-04-06 13:26 UTC, alpeb commented on linkerd.io/content/2.10/tasks/manually-rotating-control-plane-tls-credentials.md
> +  | yq -r .identityTrustAnchorsPEM - > original-trust.crt
Ok good point. I've just pushed a change moving back to `yq e`.

2021-04-06 17:14 UTC, lagalbra commented on linkerd.io/content/2.10/tasks/manually-rotating-control-plane-tls-credentials.md
> +  | yq -r .identityTrustAnchorsPEM - > original-trust.crt
Across all 3 files, the command should be `yq e .global.identityTrustAnchorsPEM -`; some of the files are missing the last `-` and/or the starting `.global`

2021-04-06 18:56 UTC, alpeb commented on linkerd.io/content/2.10/tasks/manually-rotating-control-plane-tls-credentials.md
> +  | yq -r .identityTrustAnchorsPEM - > original-trust.crt
Ok I've just added the missing dash. As for `.global`, that disappeared in version `2.10`

2021-04-06 19:07 UTC, lagalbra approved these changes

2021-04-08 14:27 UTC, merged