Blog updates
linkerd/website pull request #1024
Opened 2021-04-05 17:31 UTC by PaulMichaelArmstrong

• Added March community meeting recap
• Added Jason and Alejandro as authors
• Added author image for Alex

Signed-off-by: Paul Armstrong <paul@buoyant.io>

2021-04-05 17:39 UTC, cpretzer requested changes
Couple of small notes here

2021-04-05 17:39 UTC, cpretzer commented on linkerd.io/content/blog/march-linkerd-community-meeting.md
> +Linkerd 2.10 is now available and is the lightest it has ever been. Many of the previous defaults are now extensions, providing users with a lot more control. We have also released the 21.3.4 edge re
What do you think about moving the graduation bit to its own line? It's significant and feels a little buried here.

Also, it should read `Another really big piece of news...`

2021-04-05 17:39 UTC, cpretzer commented on linkerd.io/content/blog/march-linkerd-community-meeting.md
> +We are setting the stage for policy in 2.11 and will continue consolidating control plane components. Join our next community meeting for more details.
Do we have a link to sign up for the next community meeting? That would be great to have here.

2021-04-05 17:39 UTC, cpretzer commented on linkerd.io/content/blog/march-linkerd-community-meeting.md
> +In 2.10, we've modularized the control plane. Users can now choose between multiple opt-in extensions; gaining more control over their service mesh implementation and making Linkerd even more lightwe
Link to the blog post here

2021-04-05 17:39 UTC, cpretzer commented on linkerd.io/content/blog/march-linkerd-community-meeting.md
> +This month we nominated four great Linkerd Hero candidates: Fredrik Klingenberg and Henry Hagnas for sharing their amazing Linkerd story; Christian Hüning for always jumping in on the Linkerd Slack t
This should be `Mayank`

2021-04-05 17:42 UTC, PaulMichaelArmstrong commented on linkerd.io/content/blog/march-linkerd-community-meeting.md
> +Linkerd 2.10 is now available and is the lightest it has ever been. Many of the previous defaults are now extensions, providing users with a lot more control. We have also released the 21.3.4 edge re
@CathPag

2021-04-05 17:42 UTC, PaulMichaelArmstrong commented on linkerd.io/content/blog/march-linkerd-community-meeting.md
> +We are setting the stage for policy in 2.11 and will continue consolidating control plane components. Join our next community meeting for more details.
@CathPag

2021-04-05 17:43 UTC, PaulMichaelArmstrong commented on linkerd.io/content/blog/march-linkerd-community-meeting.md
> +In 2.10, we've modularized the control plane. Users can now choose between multiple opt-in extensions; gaining more control over their service mesh implementation and making Linkerd even more lightwe
@CathPag CTA at the end? "Read more about it here."

2021-04-05 17:45 UTC, CathPag commented on linkerd.io/content/blog/march-linkerd-community-meeting.md
> +This month we nominated four great Linkerd Hero candidates: Fredrik Klingenberg and Henry Hagnas for sharing their amazing Linkerd story; Christian Hüning for always jumping in on the Linkerd Slack t
Yes! Thanks for the catch, @cpretzer

2021-04-05 17:46 UTC, CathPag commented on linkerd.io/content/blog/march-linkerd-community-meeting.md
> +In 2.10, we've modularized the control plane. Users can now choose between multiple opt-in extensions; gaining more control over their service mesh implementation and making Linkerd even more lightwe
Oops, did I forget the link? It should be: Learn more in our [blog post on the release](https://linkerd.io/2021/03/11/announcing-linkerd-2.10/).

2021-04-05 17:52 UTC, PaulMichaelArmstrong commented on linkerd.io/content/blog/march-linkerd-community-meeting.md
> +In 2.10, we've modularized the control plane. Users can now choose between multiple opt-in extensions; gaining more control over their service mesh implementation and making Linkerd even more lightwe
No. I am moving to fast and didn't realize that was already in there and I missed hyperlinking it.

2021-04-05 17:58 UTC, PaulMichaelArmstrong commented on linkerd.io/content/blog/march-linkerd-community-meeting.md
> +We are setting the stage for policy in 2.11 and will continue consolidating control plane components. Join our next community meeting for more details.
Not yet. I am checking with Stephanie about it.

2021-04-05 19:20 UTC, cpretzer approved these changes
Once we get the link for the April meeting, this will be good to go

2021-04-06 21:39 UTC, PaulMichaelArmstrong commented
@cpretzer They are wanting to try the platform before posting the next meeting. Can we merge and we'll add the link later?

2021-04-06 21:41 UTC, merged

2021-04-06 21:41 UTC, cpretzer commented
> @cpretzer They are wanting to try the platform before posting the next meeting. Can we merge and we'll add the link later?

Mergified! 😄