Added new terms, FAQ schema, and meta description
linkerd/website pull request #1056
Opened 2021-04-23 17:59 UTC by CathPag

2021-04-23 19:22 UTC, cpretzer reviewed
Just a couple of small notes

2021-04-23 19:22 UTC, cpretzer commented on linkerd.io/content/service-mesh-glossary/_index.md
> +      across clusters, in a way that's secure even across the open Internet.
what do you think of replacing `open` with `public`?

2021-04-23 19:22 UTC, cpretzer commented on linkerd.io/content/service-mesh-glossary/_index.md
> +way that's secure even across the open Internet, and is fully transparent
@CathPag See note above about replacing `open` with `public`

2021-04-23 19:26 UTC, CathPag commented on linkerd.io/content/service-mesh-glossary/_index.md
> +      across clusters, in a way that's secure even across the open Internet.
sure

2021-04-23 19:27 UTC, CathPag commented on linkerd.io/content/service-mesh-glossary/_index.md
> +way that's secure even across the open Internet, and is fully transparent
ok

2021-04-23 22:35 UTC, cpretzer requested changes

2021-04-23 22:35 UTC, cpretzer commented on linkerd.io/content/service-mesh-glossary/_index.md
> +      across clusters, in a way that's secure even across the open Internet.
Great! Please make the changes and then we can get this merged :)

2021-04-26 15:33 UTC, CathPag commented
done

2021-04-26 19:28 UTC, cpretzer approved these changes

2021-04-26 19:28 UTC, merged