Fix load balancing link
linkerd/website pull request #1065
Opened 2021-05-04 17:49 UTC by obrienrobert

For both 2.9 and 2.10, the `its own EWMA load balancing` link within the https://linkerd.io/2.9/tasks/using-ingress/ and https://linkerd.io/2.10/tasks/using-ingress/ doc is dead.

2021-05-04 22:01 UTC, cpretzer requested changes
Thanks for helping with this @obrienrobert

The link validation check reports that the URL is invalid, and the relative URLs for the links don't need the `..`

Can you try setting the URL to `/features/load-balancing` ?

2021-05-04 22:10 UTC, cpretzer commented
Thanks for the quick fix @obrienrobert It looks like some of our redirect rules cause the link to go to the linkerd 1 docs.

I'll have a look to figure out what the correct relative path is for these pages. I'll put an update here when I sort it out.

2021-05-04 22:35 UTC, obrienrobert commented
@cpretzer no problem. Please feel free to close this PR if you think that a new PR is required to fix any additional issues with the links. It's just something I came across when reading through the docs.

2021-05-05 04:43 UTC, cpretzer commented
@obrienrobert thanks again for this PR. I found a few more malformed links, and updated them in #1066 

I'm going to close this PR, and please keep up the great work on making the docs awesome. We're looking forward to your next PR!

2021-05-05 04:44 UTC, closed without merging