New glossary terms
linkerd/website pull request #1071
Opened 2021-05-07 17:17 UTC by CathPag

2021-05-07 17:32 UTC, CathPag commented
Whoever merges this, could you please verify the links to the Linkerd docs of the reliability term are correct?

2021-05-11 22:23 UTC, wmorgan reviewed
Links should be relative

2021-05-11 22:23 UTC, wmorgan commented on linkerd.io/content/service-mesh-glossary/_index.md
> +timeouts](https://linkerd.io/2.10/features/retries-and-timeouts/)
```suggestion
timeouts](/2/features/retries-and-timeouts/)
```

2021-05-11 22:23 UTC, wmorgan commented on linkerd.io/content/service-mesh-glossary/_index.md
> +in intelligent ways](https://linkerd.io/2.10/features/load-balancing/),
```suggestion
in intelligent ways](/2//features/load-balancing/),
```

2021-05-11 22:23 UTC, wmorgan commented on linkerd.io/content/service-mesh-glossary/_index.md
> +by [shifting traffic](https://linkerd.io/2.10/features/traffic-split/)
```suggestion
by [shifting traffic](/2//features/traffic-split/)
```

2021-05-13 15:00 UTC, cpretzer commented
The [validation checks](https://github.com/linkerd/website/pull/1071/checks?check_run_id=2567728391#step:5:37) indicate that the URLs for `/2/...` don't exist and this is correct because the redirect is not part of the validation, as far as I can tell. For example, if you go directly to https://linkerd.io/2/features/automatic-mtls, the page will redirect to https://linkerd.io/2.10/features/automatic-mtls.

This doesn't appear to work in the context of these validation checks, which requires some investigation.

In the short term, I think we can update the glossary links to go directly to the latest version, but the long term fix will require more effort because we don't want to have to update these links for every new release of Liinkerd.

2021-05-13 15:00 UTC, cpretzer requested changes
See note in the PR about using the latest version in the URLs

2021-05-13 15:02 UTC, wmorgan commented
Weird, we have these /2/ links all over the place, don't we? Why would the validation fail just for these?

2021-05-17 05:17 UTC, cpretzer commented
I'll dig into it tomorrow

On Thu, May 13, 2021 at 8:02 AM William Morgan ***@***.***>
wrote:

> Weird, we have these /2/ links all over the place, don't we? Why would the
> validation fail just for these?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/linkerd/website/pull/1071#issuecomment-840621438>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXFPR6IR267A4CGHCHXE4TTNPSYTANCNFSM44KTIL3Q>
> .
>

2021-05-24 15:16 UTC, CathPag commented
@cpretzer just following up on this. Could we get it live early this week?

2021-05-24 17:04 UTC, cpretzer requested changes

2021-05-24 17:07 UTC, cpretzer commented
> Weird, we have these /2/ links all over the place, don't we? Why would the validation fail just for these?

We do have `/2/` links in other places, so this is unexpected. Once the URLs are cleaned up, I'll merge this and fix it from a separate branch.

If you go to https://linkerd.io/2/features/load-balancing (or any of the URLs) the redirects work. So, it seems like there is something going awry with the CI checks and the redirects, but I'd expect all the `/2/` links to fail

2021-05-25 04:11 UTC, cpretzer approved these changes
The changes look good, despite the failing CI checks. 

To expedite getting this content out, I'm going to merge this and create a new branch to update the links.

2021-05-25 04:14 UTC, merged