May Community Meeting Recap Part 1
linkerd/website pull request #1099
Opened 2021-06-16 16:31 UTC by CathPag

@C-Mejlak, 

@PatrickHeneise may already have asked you. Would love to get some support getting Linkerd blogs published. Charles and Jason are busy with other stuff and, if you could help, that'd be great. 

This is an example that is probably on the time-intensive side as it includes a lot of videos that need video schema. Most blogs don't have videos.

To dos here are:

- Add all video schema
- make sure metadata is complete (there are some fields for date, is that autogenerated?
- Correct any errors I snuck in 

Ideally, turnaround time would be 24 hours. I guess (or hope) this is a smaller task you can squeeze in before or after a bigger chunk. Do you think this would be doable?

2021-06-16 18:28 UTC, cpretzer requested changes
@CathPag the file needs to have an `.md` extension so that the static site builder picks it up. Can you rename the file please?

2021-06-16 18:28 UTC, cpretzer commented on linkerd.io/content/blog/may-community-meeting-recap-part-1
> +date =
Can you add a date so that the post shows up in the sort?

2021-06-17 07:14 UTC, CathPag commented on linkerd.io/content/blog/may-community-meeting-recap-part-1
> +date =
That was one of my questions. Wouldn't it autopopulate? I don't know when exactly this will go live

2021-06-17 11:39 UTC, CathPag commented
**Why the future of the cloud will be built on Rust**
In his Cloud Native Rust Day talk, Oliver Gould notes that system programming differs from app programming and requires a different language like Rust.  

**Panel Discussion: Rust in the Cloud**
In this panel discussion, the speakers agreed that Rust front-loads the application maintenance burden and is extremely secure and performant. 

**Scheduling 68k COVID Tests with Linkerd**
Dom DePasquale and Shawn Smith from the Pennsylvania State University discussed how they scheduled 68,000 COVID tests before the fall semester started. 

**Rapid Experimentation Simplified with Linkerd**
When Alexander Simon Jones worked at a multi-national financial institution his team used Linkerd to simplify experimentation. 

**Tap Tap, Debugging an App with your Service Mesh**
In his ServiceMeshCon talk, Jason Morgan shows how easy it is to debug an app with Linkerd. The tap tool inspects traffic flowing through the mesh. 

**Creating Chaos in the University with Linkerd and Chaos Mesh**
Jossie Bismarck Castrillo Fajardo and Sergio Arnaldo Méndez Aguilar, discuss how they used Chaos Mesh and Linkerd to inject faults and failures.

**Panel: The State of Service Mesh** 
According to the panelists, enterprises must decide whether they want to write and maintain code that a service mesh provides or have a platform team that supports it.

**Compliance the Easy Way: Zero-conf mTLS for Dev and Smooth Day-2 for Ops**
Christian Hüning and Lutz Behnke discuss how they implemented mTLS without needing their dev team to do any work. 

**Seamless Multi-Cluster Communication and Observability with Linkerd**
Max Körbächer from Liquid Reply provided a great breakdown of when it makes.

**Keynote: Linkerd vs. COVID-19: Addressing the global Pandemic with a Service Mesh**
William Morgan shares some examples of how organizations like NIH, Clover Health, Penn State, and H-E-B, have been using Linkerd in their effort to face COVID-19 challenges.

**Overview and State of Linkerd**
William Morgan and Matei David delivered a quick overview of the state of Linkerd, why we are witnessing an increase in adoption, and what drives this great and welcoming community.

2021-06-19 08:08 UTC, PatrickHeneise commented
@C-Mejlak can you add the faq and video schema?

2021-06-21 05:42 UTC, C-Mejlak commented
@PatrickHeneise this is merged in https://github.com/linkerd/website/pull/1100 @CathPag could you please close this one

2021-06-21 07:10 UTC, closed without merging