tasks: add new `linkerd-smi` getting started guide
linkerd/website pull request #1138
Opened 2021-08-02 12:56 UTC by Pothulapati

This PR adds a new task to get started with the
`linkerd-smi` extension where we go through the
installation and try it with a sample application

Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

2021-08-03 18:11 UTC, cpretzer commented
@Pothulapati is this ready to be merged after review? Or do we need to wait for the `2.11` release?

2021-08-03 18:44 UTC, cpretzer requested changes
One small change to remove the reference to `Linkerd-Jaeger` and this is good to go.

I walked through the steps and everything looks good.

One thing I found useful during my testing was to look at the logs for the `smi-adaptor` pod, so an example of that might be useful, but not necessary

2021-08-03 18:44 UTC, cpretzer commented on linkerd.io/content/2.10/tasks/linkerd-smi.md
> +The first step is installing the Linkerd-Jaeger extension onto your cluster.
Should this be `Linkerd-SMI`?

2021-08-04 11:08 UTC, Pothulapati commented
@cpretzer Updated!

> @Pothulapati is this ready to be merged after review? Or do we need to wait for the 2.11 release?

Yep, Should be ready to be merged after review!

2021-08-04 16:15 UTC, cpretzer approved these changes

2021-08-04 16:16 UTC, merged