blog: Add service account tokens post
linkerd/website pull request #1254
Opened 2021-12-10 10:58 UTC by Pothulapati

This PR adds a blog post for the new service account token changes
in the https://github.com/linkerd/linkerd2/pull/7117

We start from what service accounts are, and then explain about the
linkerd integration followed by the latest changes.

Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

2021-12-10 17:58 UTC, cpretzer requested changes
Great post @Pothulapati ! Just a few comments for cosmetic changes

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +right? But how does the identity component ensure it's issuing certificate
Change to "...ensure it is issuing a certificate for a proxy in the cluster and not some intruder trying to communicate...`

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +proxies itself? Now, Let's dive into that :)
Replace "Now, let's dive into that" with "We'll answer those questions in this blog post. Let's dive in"

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +by the application inside to prove its identity to other components that its
Replace "its" with "it is"

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +part of the kubernetes cluster. These are attached as a volume into your Pod,
Uppercase "Kubernetes" for consistency

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +Kubernetes API Services to pods. This is done by attaching a ClusterRole (with
Use backticks on `ClusterRole` for consistency

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +using a `ClusterRoleBinding`. and then specifying the same Service Account in the
Change "and then specifying..." to "Then we can specify the same `ServiceAccount`..."

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +used all of these as the proxies *never* talk to the Kubernetes API directly.
"used" -> "uses"

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +Once a token is verified, Only after that the identity component issues a certificate
remove "Only after that"

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +Whenever a meshed request is received or being sent. The relevant metrics
change "...or being sent, the relevant..."

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +by allowing users to specify service accounts of the clients that should be allowed
change "by allowing" to "to enable"

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +In the above example, we are allowing workloads that use the `web` service account
change "allowing" to "permitting"

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +Though all of this is great, There's still a catch. This token is aimed at the
change "... There's still a..." to "... there's still a..."

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +applications to talk to the kubernetes API and not specifically for Linkerd.
Uppercase `Kubernetes` for consistency

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +Linkerd. Currently, We skip pod injection if that is the case.
Change "Currently, we skip..." to "As of Linkerd 2.11, we skip pod injection if the token auto-mount is disabled."

2021-12-10 17:58 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +for Linkerd, along with a 24h expiry(just like that of identity expiration). This
add space after "expiry"

2021-12-13 07:12 UTC, Pothulapati commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +used all of these as the proxies *never* talk to the Kubernetes API directly.
used right? because they were only present previously and we never used then. They are not present after the latest changes. 🤔

2021-12-16 18:48 UTC, cpretzer commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +used all of these as the proxies *never* talk to the Kubernetes API directly.
ah, you're right. I lost the tense there. :)

2021-12-16 18:49 UTC, cpretzer approved these changes
LGTM 🚢

2021-12-20 15:47 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +Linkerd uses mTLS to secure communication between services. You can read
```suggestion
Linkerd uses mutual TLS (mTLS) to secure communication between services. You can read
```

2021-12-20 15:47 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +the mTLS magic is possible because the control-plane (specifically the
Terminology and capitalization notes: 
* I suggest "control plane" instead of "control-plane" for consistency with other posts.
* I suggest using either `ServiceAccount` to refer to the actual K8s object, or "service account" for the general concept, but avoiding "Service Account".
* Referring to the proxy certs as "leaf certs" isn't wrong but IMO it's a little distracting since we're not talking about the implications of leaf vs non-leaf. I would just refer to them as certs.
* I would just use "pod" everywhere instead of Pod.

2021-12-20 15:47 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +title: Service Account Tokens in Linkerd
IMO the exciting bit here is the move to *bound* ServiceAccount tokens. I think the post would be stronger if it were titled something like "Using Kubernetes's new bound ServiceAccounts for secure identity", and started with a general comment about Linkerd's emphasis on security and simplicity. Happy to suggest a paragraph or two if you like that approach.

2021-12-20 15:47 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +Linkerd's new Policy Enforcement feature allows users to specify set of clients
Terminology: I would call this either "authorization policy" which is what we use in the docs.

2021-12-20 15:47 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +or a proxy in the cluster and not some intruder trying to communicate with
```suggestion
to a proxy in the cluster and not some intruder trying to communicate with
```

2021-12-22 15:40 UTC, wmorgan reviewed
Left a lot of suggested edits and added the standard footer at the end.

Please add an image as well -- follow the pattern in previous blog posts.

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +Security is a first-class concern for Linkerd. We recently added support for
```suggestion
Security is a first-class concern for Linkerd. It plays a critical role in enhancing the overall security of the
system, and this is only possible if Linkerd *itself* is secure. We recently added support for
```

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +the mTLS magic is possible because the control plane (specifically the
```suggestion
```suggestion
Linkerd provides mutual TLS (mTLS) to secure communication between workloads. Central to
any type of communication security is the notion of *identity*—as discussed in the
[Kubernetes engineer’s guide to mTLS](https://buoyant.io/mtls-guide/), without identity you
have no authenticity, and without authenticity you do not have secure communication.
All of Linkerd's mTLS magic is possible because the control plane (specifically the
```

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +This is not just a Linkerd problem right? A lot of components or K8s controllers
```suggestion
This is not just a Linkerd problem. A lot of components or K8s controllers
```

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +We will see later how we even stopped using these in the latest changes).
I don't quite understand this bit. What does "these" refer to? "Linkerd never used all of these" suggests that it used a portion of the ConfigMap, but what is in the ConfigMap besides that one certificate? (Also we should probably describe what kube-root-ca.crt is)

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +request that is called every time a new certificate is needed(24h by default).
```suggestion
request that is called every time a new certificate is needed (24 hours, by default).
```

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +
```suggestion
## So how does Linkerd validate that its proxies are who they say they are?

```

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +Whenever a meshed request is received or being sent, the relevant metrics
```suggestion
### How does Linkerd provide workload identity?

Linkerd takes a beautiful (in my mind) simplifying step here: the service accounts aren't just used
to validate that the proxies are who they say they are, they're used as the *basis of the workload's
identity itself*. This gives us a workload identity that is already tied to the capabilities granted to the
pod, and means that we can provide mTLS without any additional configuration! This is the secret
behind Linkerd's ability to provide on-by-default mTLS for all meshed pods.

Whenever Linkerd established a mutual TLS connection between two endpoints,
the identity exchanged is that of the service account on either side. This identity
is even wired into Linkerd's metrics: whenever a meshed request is received or being sent, the relevant metrics
```

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +We have added the support for auto-mount bounded service account tokens. Instead
```suggestion
To address these challenges, starting from [edge-21.11.1](https://github.com/linkerd/linkerd2/releases/tag/edge-21.11.1)
we have added the support for auto-mount bounded service account tokens. Instead
```

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +feature. Bounded Service Account Tokens which got GA'ed in Kubernetes v1.20 are just
```suggestion
feature. Bounded Service Account Tokens (GA as of in Kubernetes v1.20) are just
```

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +like the default tokens except that they could be bounded for a different
Needs a better description IMO

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +above.
```suggestion
Kubernetes, and thus does not affect any of Linkerd's existing functionality around identity and policy discussed
above.
```

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +Kubernetes API. Thus, giving us a nice separation of concerns.
```suggestion
to verify themselves with identity, and cannot be used talk to the
Kubernetes API, giving us a nice separation of concerns.
```

2021-12-22 15:40 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +by integrating the latest developments in Kubernetes.
```suggestion
In this post, we described the motivation for moving to Kubernetes's new bound service account tokens,
which reduce the scope of Linkerd's access to the Kubernetes API to the bare minimum necessary to support
its security features. We also uncovered some of the inner workings of how the
control plane validates the proxies before issuing the certificates, and saw how Linkerd uses Kubernetes's service accounts as a primitive to build features like authorization policy.

Our goal with Linkerd is to provide world-class security for Kubernetes users without imposing a burden on them. By relying on service accounts, we can provide on-by-default mutual TLS with zero config for all meshed pods,
the moment you install Linkerd. And with bound service accounts, the implementation is even more secure
than before.

## Linkerd is for everyone

Linkerd is a [graduated project](/2021/07/28/announcing-cncf-graduation/) of the
[Cloud Native Computing Foundation](https://cncf.io/). Linkerd is [committed to
open
governance.](https://linkerd.io/2019/10/03/linkerds-commitment-to-open-governance/)
If you have feature requests, questions, or comments, we'd love to have you join
our rapidly-growing community! Linkerd is hosted on
[GitHub](https://github.com/linkerd/), and we have a thriving community on
[Slack](https://slack.linkerd.io/), [Twitter](https://twitter.com/linkerd), and
the [mailing lists](https://linkerd.io/2/get-involved/). Come and join the fun!

```

2021-12-23 05:36 UTC, Pothulapati commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +```yaml
I' +1 on keeping it, as it shows this in reality, instead of just trying to explain in words! 🤔

2021-12-23 07:18 UTC, Pothulapati commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +We will see later how we even stopped using these in the latest changes).
Hmm, `kube-root-ca.crt` is a separate configmap that gets attached to authenticate with the API server. I updated this para to explain that.

2021-12-23 07:21 UTC, Pothulapati commented
@wmorgan Addressed them. Thanks for all the suggestions.

For the image part, I can't really find a need for a image in the blog post as the content didn't seem to have any flows that can be drawn. Do you have any ideas?

I've attached https://github.com/kubernetes/community/blob/master/icons/png/resources/labeled/sa-256.png for the thumbnail part though, as its the service account resource logo!

2021-12-23 20:16 UTC, wmorgan commented
@Pothulapati Sorry I wasn't more clear. The blog posts on linkerd.io each have an evocative image, usually pulled from Unsplash. It's used at the top of the article and also in the thumbnail and Opengraph tags. Something like https://unsplash.com/photos/3wPJxh-piRw .

2021-12-24 05:18 UTC, Pothulapati commented
@wmorgan That image looks perfect, added it!

2021-12-27 17:36 UTC, wmorgan approved these changes
Some very minor nits. Otherwise looks great. Shipit!

2021-12-27 17:36 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +title: Using Kubernetes's new Bound Service Account Tokens for secure workload Identity
```suggestion
title: Using Kubernetes's new Bound Service Account Tokens for secure workload identity
```

2021-12-27 17:36 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +date: 2021-12-24T00:00:00Z
```suggestion
date: 2021-12-27T00:00:00Z
```

2021-12-27 17:36 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +date: 2021-12-24T00:00:00Z
Or whenever :)

2021-12-27 17:36 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +## Bounded Service Account Tokens
```suggestion
## Bound Service Account Tokens
```

2021-12-27 17:36 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +feature. Bounded Service Account Tokens (GA as of in Kubernetes v1.20) feature allows
```suggestion
feature. Bound Service Account Tokens (GA as of in Kubernetes v1.20) feature allows
```

2021-12-27 17:36 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +### Authorization Policy
```suggestion
## Authorization Policy
```

2021-12-27 17:36 UTC, wmorgan commented on linkerd.io/content/blog/linkerd-service-account-tokens.md
> +### How does Linkerd provide workload identity?
```suggestion
## How does Linkerd provide workload identity?
```

2021-12-28 18:44 UTC, merged