improve installation guide
linkerd/website pull request #1401
Opened 2022-08-15 14:53 UTC by wmorgan

* Point out that Helm is recommended for production installations.
* Remove multi-stage instructions.
* Wordsmithing.

Signed-off-by: William Morgan <william@buoyant.io>

2022-08-15 15:10 UTC, kflynn requested changes
One place where some words are duplicated – looks good to me other than that, though!

2022-08-15 15:10 UTC, kflynn commented on linkerd.io/content/2.11/tasks/install.md
> +which add additional features i.e `viz`, `multicluster` and `jaeger`. See
s/which add additional//

2022-08-22 21:49 UTC, wmorgan commented on linkerd.io/content/2.11/tasks/install.md
> +may be hosted on a cloud provider or may be running locally via Minikube or
Agreed. I've removed this bit entirely.

2022-08-22 21:49 UTC, wmorgan commented on linkerd.io/content/2.11/tasks/install.md
> +which add additional features i.e `viz`, `multicluster` and `jaeger`. See
Ty!

2022-08-22 22:00 UTC, kleimkuhler approved these changes
Overall looks good. Since these changes are made for 2.11 though we'll want to make sure 2.12 gets similar edits — different only in that 2.12 now has the `linkerd install --crds` step.

2022-08-22 22:49 UTC, merged