Add protocol detection timeout log message to protocol detection doc
linkerd/website pull request #1482
Opened 2022-09-02 16:17 UTC by dtaskai

Fixes #1480, added the protocol detection log message to the docs for better SEO.

Signed-off-by: Dominik Táskai <dominik.taskai@leannet.eu>

2022-09-02 18:22 UTC, hawkw requested changes

2022-09-02 18:22 UTC, hawkw commented on linkerd.io/content/2.12/features/protocol-detection.md
> +are experiencing 10-second delays when establishing connections, you are
this is pretty nitpicky, but I don't love the use of the word "receive" here. how about something like this:
> If your proxy logs contain messages like `protocol detection timed out after 10s`, or you are experiencing 10-second delays [...]

2022-09-02 18:26 UTC, dtaskai commented on linkerd.io/content/2.12/features/protocol-detection.md
> +are experiencing 10-second delays when establishing connections, you are
It also didn't sit well with me, but now I see why :smile:, thank you @hawkw!

2022-09-04 14:14 UTC, wmorgan approved these changes
Thank you!

2022-09-22 16:43 UTC, wmorgan commented
@hawkw you good with this?

2022-09-29 16:21 UTC, hawkw approved these changes
Looks good to me!

2022-09-29 16:21 UTC, merged