Moved HTTPRoute reference doc into its own page
linkerd/website pull request #1590
Opened 2023-03-21 16:45 UTC by alpeb

Moved out of Authorization Policy given it's also used for Header-Based routing which is unrelated to Auth.

Also added missing fields in the ref.

Upcoming: Header-Based routing tutorial

2023-04-06 18:55 UTC, hawkw reviewed
I left some potential suggestions on the docs. I know a lot of this wasn't added in this PR, but I hope the suggestions are still helpful!

2023-04-06 18:55 UTC, hawkw commented on linkerd.io/content/2-edge/reference/httproute.md
> +| `backendRefs`| An array of [HTTPBackendRefs](#httpbackendref) to declare where the traffic should be routed to (only to be used with Service parentRefs).|
maybe:
```suggestion
| `backendRefs`| An array of [HTTPBackendRefs](#httpbackendref) to declare where the traffic should be routed to (only allowed with Service [parentRefs](#parentreference)).|
```

2023-04-06 18:55 UTC, hawkw commented on linkerd.io/content/2-edge/reference/httproute.md
> +| `weight`| Proportion of requests sent to this backend.|
a backend ref can also have a namespace: https://github.com/linkerd/linkerd2/blob/6e28aefc774f8746d8cc7536535261da5d135a3c/charts/linkerd-crds/templates/policy/httproute.yaml#L977

2023-04-06 18:55 UTC, hawkw commented on linkerd.io/content/2-edge/reference/httproute.md
> +otherwise `smiley` is served:
maybe:
```suggestion
a `x-faces-user: testuser` header in the request, the request is routed to the
`smiley2` backend Service. Otherwise, the request is routed to the `smiley`
backend Service.
```

2023-04-08 11:06 UTC, alpeb commented on linkerd.io/content/2-edge/reference/httproute.md
Ok I think it's fine to have all resource names be just capitalized, including HTTPRoute, without backticks :+1:

2023-04-08 11:15 UTC, alpeb commented on linkerd.io/content/2-edge/reference/httproute.md
> +
I'm not sure we should do that, given they start talking about Gateway listeners right off the bat, and deal with resources we don't support, which could be confusing?

2023-04-08 11:16 UTC, alpeb commented on linkerd.io/content/2-edge/reference/httproute.md
> +
See my comment above

2023-04-08 11:17 UTC, alpeb commented on linkerd.io/content/2-edge/reference/httproute.md
> +A reference to the [Servers] this `HTTPRoute` is a part of.
:+1:

2023-04-08 11:22 UTC, alpeb commented on linkerd.io/content/2-edge/reference/httproute.md
> +| `weight`| Proportion of requests sent to this backend.|
Good point, I'll add that. But do we actually support cross-namespace traffic without ReferenceGrants?

2023-04-08 11:24 UTC, alpeb commented
Thanks for the comments @hawkw , this is ready for review again.

2023-04-10 17:18 UTC, hawkw reviewed
couple last suggestions

2023-04-10 17:18 UTC, hawkw commented on linkerd.io/content/2-edge/reference/httproute.md
> +
good point!

2023-04-10 17:18 UTC, hawkw commented on linkerd.io/content/2-edge/reference/httproute.md
> +| `kind`| The kind of the referent. This must be set to either "Server" or "Service".|
nit, TIOLI:
```suggestion
| `kind`| The kind of the referent. This must be either "Server" or "Service".|
```

2023-04-10 19:52 UTC, alpeb commented on linkerd.io/content/2-edge/reference/httproute.md
> +A reference to the parent resource this HTTPRoute is a part of.
I actually had a section at the beginning of the doc explaining this difference, but your point is taken, so I'm moving that into this subsection instead :+1:

2023-04-10 19:56 UTC, hawkw commented on linkerd.io/content/2-edge/reference/httproute.md
> +request routing.
maybe the phrase "dynamic request routing" should link to the dynamic request routing docs. we can add the link in that branch if this one merges first...

2023-04-10 19:56 UTC, hawkw commented on linkerd.io/content/2-edge/reference/httproute.md
> +HTTPRoutes can also be attached to a Service, in order to classify requests
not sure if i love the use of the term "classify" here, since that feels a little overloaded with response classification. how about 
```suggestion
HTTPRoutes can also be attached to a Service, in order to route requests
```

2023-04-10 20:14 UTC, hawkw commented
looks like something's busted: https://github.com/linkerd/website/actions/runs/4660760367/jobs/8249216653?pr=1590#step:5:19

2023-04-10 20:17 UTC, adleong commented on linkerd.io/content/2-edge/reference/httproute.md
> +HTTPRoutes can also be attached to a Service, in order to classify requests
+1

2023-04-10 20:17 UTC, adleong approved these changes

2023-04-10 20:49 UTC, kflynn requested changes
I definitely like moving the `HTTPRoute` spec into its own doc! I made a couple of suggestions about referring to it, though...

2023-04-10 20:49 UTC, kflynn commented on linkerd.io/content/2-edge/reference/authorization-policy.md
> +When attached to a [Server], an `HTTPRoute` resource represents a subset of the
Maybe just make this mention (or all mentions?) of `HTTPRoute` a link to the spec, rather than having the one-sentence paragraph at line 153?

2023-04-10 20:49 UTC, kflynn commented on linkerd.io/content/2-edge/reference/authorization-policy.md
> +Please refer to HTTPRoute's full [spec](../httproute/).
Maybe just drop this sentence in favor of linking out from mentions of `HTTPRoute`?

2023-04-10 21:16 UTC, alpeb commented on linkerd.io/content/2-edge/reference/authorization-policy.md
> +Please refer to HTTPRoute's full [spec](../httproute/).
This paragraph briefly describes HTTPRoute in the context of Authorization Policy and the title is a lilnk with an HTTPRoute anchor, targeted from other places in this doc. That's why other references in this doc point to this paragraph and then I have this sentence to clearly point out to the other doc with the full reference. Makes sense?

2023-04-10 23:04 UTC, hawkw approved these changes

2023-04-10 23:20 UTC, kflynn approved these changes
Let's get this landed. 🙂

2023-04-10 23:20 UTC, merged