[WIP] circuit breaking reference documentation
linkerd/website pull request #1598
Opened 2023-04-07 21:54 UTC by hawkw

2023-04-07 22:04 UTC, adleong commented on linkerd.io/content/2-edge/reference/circuit-breaking.md
> +The following annotations configure failure accrual:
In the above paragraph you say that these annotations are added to a Service, but that might be easy to miss if someone is skipping right to the configuration reference.  I think it's worth being extra loud about how the configuration works: 

Set this annotation on a Service to enable meshed clients to use circuit breaking when sending to that Service.

2023-04-10 18:47 UTC, adleong approved these changes

2023-04-10 18:59 UTC, kflynn requested changes
I have some questions and minor nits, but this looks _very_ helpful overall, thanks!!

2023-04-10 19:03 UTC, hawkw commented on linkerd.io/content/2-edge/reference/circuit-breaking.md
> +considered unavailable and a different backend may be selected.
i wanted to have this link to the HTTPRoute docs section but am waiting for #1590 to merge so that i can add the links. i think changing it to refer specifically to HTTPRoute/backendRef is a good call regardless!

2023-04-10 19:27 UTC, hawkw commented on linkerd.io/content/2-edge/reference/circuit-breaking.md
> +HTTPRoute](../httproute/#httpbackendref), the entire backend Service will be
this link is going to be broken until #1590 merges, but i wanted to go ahead and add the link so i didn't forget to later.

2023-04-10 19:55 UTC, kflynn approved these changes
Hit it! 🙂

2023-04-10 23:21 UTC, merged