Add Bouyant block on home page
linkerd/website pull request #1606
Opened 2023-04-14 17:57 UTC by dered-dev

**ADD**: New block for "Bouyant" in home page
**ADD**: Prefix css properties
**Update**: Stats list in home page

2023-04-24 14:21 UTC, kflynn requested changes
There are actually many places beyond William's note where "b**uo**yant" is spelled "b**ou**yant" instead, including filenames and such; we need to get all of those corrected so that we don't all get very confused down the road. 🙂 

Looks good other than that, though! 🙂

2023-04-24 19:52 UTC, wmorgan reviewed
After staring at this for a while, I think we should just remove the CTA text entirely.

2023-04-24 19:52 UTC, wmorgan commented on linkerd.io/layouts/partials/homepage/cta-buoyant.html
> +        <p class="has-text-weight-medium has-text-color">Created by</p>
```suggestion
        <p class="has-text-weight-medium has-text-color">Linkerd was created by</p>
```

2023-04-24 19:52 UTC, wmorgan commented on linkerd.io/layouts/partials/homepage/cta-buoyant.html
> +    </div>
```suggestion
```

2023-04-24 19:52 UTC, wmorgan commented on linkerd.io/layouts/partials/homepage/stats-list.html
> +          8,000+
```suggestion
          8,500+
```

2023-04-24 20:39 UTC, dered-dev commented
@wmorgan Updated the "Linkerd was created by" block and the stats on home page

2023-04-25 18:43 UTC, kflynn commented
Forced DCO to pass since I know it's OK for @dered-dev's commits here; we'll try to sort it out for next time. 🙂

2023-04-25 18:43 UTC, kflynn approved these changes
Looks OK from here, thanks! 🙂

2023-04-25 20:08 UTC, wmorgan commented
I'd like to remove the cta-buoyant-title and cta-buoyant-subtitle entirely.

2023-04-27 17:35 UTC, kflynn approved these changes
Looks sane from here.

2023-04-27 17:35 UTC, kflynn commented
Forcing DCO and merging.

2023-04-27 17:35 UTC, merged