docs: change "Configuring Proxy Concurrency" to reflect reality
linkerd/website pull request #1611
Opened 2023-04-18 21:27 UTC by hawkw

Currently, the "Configuring Proxy Concurrency" Tasks documentation states that the proxy will always use the number of CPU cores available to the process. This is not actually correct --- if the `LINKERD2_PROXY_CORES` environment variable is unset, the proxy will always use a single-threaded runtime. If the environment variable is set, cgroup CPU limits will _also_ influence the number of worker threads spawned by the proxy, but when it is not present, the proxy will always run in single threaded mode.

Whether or not this is the ideal behavior is still open to discussion, but for now, the documentation should reflect reality. This change updates the docs to better describe the actual behavior.

Closes linkerd/linkerd2#10698

2023-04-25 18:50 UTC, kflynn requested changes
Content looks great aside from a couple of unfinished sentences. 🙂 Should this be backported to 2.12?

2023-04-25 18:50 UTC, kflynn commented on linkerd.io/content/2-edge/tasks/configuring-proxy-concurrency.md
> +- The CPU limit and CPU request must be an integer greater than or
...greater than or... what? 🙂

2023-04-25 18:50 UTC, kflynn commented on linkerd.io/content/2.13/tasks/configuring-proxy-concurrency.md
> +- The CPU limit and CPU request must be an integer greater than or
See previous comment. 🙂

2023-04-25 19:43 UTC, hawkw commented on linkerd.io/content/2-edge/tasks/configuring-proxy-concurrency.md
> +- The CPU limit and CPU request must be an integer greater than or
whoops, looks like i accidentally deleted that
```suggestion
- The CPU limit and CPU request must be an integer greater than or equal to 1.
```

2023-04-25 20:53 UTC, hawkw commented on linkerd.io/content/2.13/tasks/configuring-proxy-concurrency.md
> +- The CPU limit and CPU request must be an integer greater than or
```suggestion
- The CPU limit and CPU request must be an integer greater than or equal to 1.
```

2023-05-02 20:56 UTC, hawkw commented on linkerd.io/content/2-edge/tasks/configuring-proxy-concurrency.md
> +In this case, the kubelet use Linux `cgroup`s to enforce CPU limits for
```suggestion
In this case, the kubelet will use Linux `cgroup`s to enforce CPU limits for
```

2023-05-03 16:57 UTC, kflynn approved these changes
Looks good from here, thanks!! 🙂

2023-05-03 17:53 UTC, merged