add top-level HTTPRoute features doc
linkerd/website pull request #1657
Opened 2023-08-18 20:30 UTC by hawkw

Currently, the website doesn't really have a top-level summary of what
the HTTPRoute resource is and what it can do, similar to the
ServiceProfiles feature page. I thought this would be useful to add, as
it can be used for other documentation to link to, and will also be
useful as a place to collect all the documentation on things users can
do using HTTPRoutes. In addition, we can also add stuff about GAMMA
support and about the difference between `policy.linkerd.io` and
`gateway.networking.kubernetes.io` HTTPRoutes here, as well.

I've also updated some of the other documentation that mentions the
HTTPRoute resource to link to this page.

2023-08-18 22:53 UTC, wmorgan approved these changes

2023-08-18 22:53 UTC, wmorgan commented on linkerd.io/content/2-edge/features/httproute.md
> +Outbound HTTPRoutes are **incompatible with ServiceProfiles**. If a
If this is a temporary situation, I would call it out as such and say that this will be fixed in the future. If this is a permanent situation, I would say that ServiceProfiles override HTTPRoute behavior rather than saying they're incompatible, which to me suggests that something will break.

2023-08-18 22:53 UTC, wmorgan commented on linkerd.io/content/2-edge/features/server-policy.md
> +[`HTTPRoute`] CRDs); define the types of authentication that are required before
was this change from CR to CRDs intentional?

2023-08-18 22:53 UTC, wmorgan commented on linkerd.io/content/2-edge/features/server-policy.md
> +configured for that [`Server`]. If any [`HTTPRoute`] matches the `Server`, these
I applaud the consistency in hyperlinking though I don't know if we've followed that pattern elsewhere in the site.

2023-08-18 22:53 UTC, wmorgan commented on linkerd.io/content/2-edge/tasks/configuring-timeouts.md
> +either [HTTPRoute] [service profile](../../features/service-profiles/) for
```suggestion
either [HTTPRoute]s or [service profile](../../features/service-profiles/) for
```

2023-08-18 22:56 UTC, hawkw commented on linkerd.io/content/2-edge/features/server-policy.md
> +[`HTTPRoute`] CRDs); define the types of authentication that are required before
i thought this was a typo, but I think it's not actually...i'll undo this change!

2023-08-18 22:57 UTC, hawkw commented on linkerd.io/content/2-edge/features/httproute.md
> +Outbound HTTPRoutes are **incompatible with ServiceProfiles**. If a
i'm happy to reword this. i should mention, though, that the text of this warning is copied from other docs pages --- do you think it makes sense to also apply the same change to other instances of this warning box in the docs?

2023-08-18 23:26 UTC, hawkw commented on linkerd.io/content/2-edge/features/httproute.md
> +Outbound HTTPRoutes are **incompatible with ServiceProfiles**. If a
@wmorgan what do you think of the wording in https://github.com/linkerd/website/pull/1657/commits/3f5b04edbd0662c9cfa677a91ee9182562336804 ? I'm happy to make the same change to other warnings if you like that language!

2023-08-19 03:41 UTC, kflynn requested changes
I really like this! I've left some comments for minor things that I think need fixing, but really, they're minor, nice job. 🙂 

One final note: in some places you talk about e.g. "the `HTTPRoute` blah blah" and in other places it's "the HTTPRoute blah blah". We should probably pick one way and go with it. (IIRC the K8s standard is not to set type names in monospace, so that would be my vote, but it's not a terribly strong opinion...)

2023-08-19 03:41 UTC, kflynn commented on linkerd.io/content/2-edge/features/httproute.md
> +[HTTPRotue resource]: https://gateway-api.sigs.k8s.io/api-types/httproute/
s/HTTPRotue/HTTPRoute/

2023-08-19 03:41 UTC, kflynn commented on linkerd.io/content/2-edge/features/server-policy.md
> +  [`Server`s] only (i.e. not [`HTTPRoute`]s)
The "s" in [`Server`s] needs to move outside the brace to match your link definition.

2023-08-19 03:41 UTC, kflynn commented on linkerd.io/content/2-edge/features/server-policy.md
>  target (via an `AuthorizationPolicy`).
Might this be better as a bulleted list?

> The general pattern ... is:
> - define the traffic target ...;
> - define the types of auth...; and finally
> - define the policy... .

Thoughts? (I know you weren't editing this for content really, just occurred to me while reading it.)

2023-08-19 17:06 UTC, hawkw commented on linkerd.io/content/2-edge/features/server-policy.md
>  target (via an `AuthorizationPolicy`).
i think it might be better as a bulleted list, but i'd prefer not to make that change in this PR. 

maybe open one for that change?

2023-08-19 17:09 UTC, kflynn commented on linkerd.io/content/2-edge/features/server-policy.md
>  target (via an `AuthorizationPolicy`).
Sounds like a plan. 🙂

2023-08-19 17:12 UTC, hawkw commented
@kflynn 

> One final note: in some places you talk about e.g. "the `HTTPRoute` blah blah" and in other places it's "the HTTPRoute blah blah". We should probably pick one way and go with it. (IIRC the K8s standard is not to set type names in monospace, so that would be my vote, but it's not a terribly strong opinion...)

I tried to keep the use of monospace or not consistent with other existing uses within the same file. I didn't use monospace in the new docs I added, but I also didn't change any existing documentation. It might be worth doing a pass to make this more consistent across all the documentation, but I would prefer to do that in a separate branch.

2023-08-19 17:17 UTC, kflynn commented
Yeah, I'm good with limiting scope on this one. Thanks! 🙂

2023-08-21 16:05 UTC, hawkw commented on linkerd.io/content/2-edge/features/httproute.md
> +[HTTPRotue resource]: https://gateway-api.sigs.k8s.io/api-types/httproute/
```suggestion
[HTTPRoute resource]: https://gateway-api.sigs.k8s.io/api-types/httproute/
```

2023-08-21 16:05 UTC, hawkw commented on linkerd.io/content/2-edge/features/server-policy.md
> +  [`Server`s] only (i.e. not [`HTTPRoute`]s)
```suggestion
  [`Server`]s only (i.e. not [`HTTPRoute`]s)
```

2023-08-21 16:19 UTC, kflynn approved these changes
Hit it! 🙂

2023-08-21 16:55 UTC, merged