stable-2.14.0 upgrade instructions
linkerd/website pull request #1660
Opened 2023-08-21 17:36 UTC by alpeb

2023-08-21 18:08 UTC, adleong commented on linkerd.io/content/2-edge/tasks/upgrade.md
> +re-link your clusters. `linkerd multicluster check` will error out until you do
Will re-linking cause any downtime for multicluster services?  Does anything (data plane?) need to be rolled after relinking?  If not, we may want to reassure the user here about those things.

2023-08-21 18:45 UTC, alpeb commented on linkerd.io/content/2-edge/tasks/upgrade.md
> +re-link your clusters. `linkerd multicluster check` will error out until you do
This doesn't cause any downtime; I'll add a clarification. No special data plane rollouts required besides what's already described in the top sections.

2023-08-21 18:55 UTC, adleong approved these changes

2023-08-21 19:32 UTC, hawkw requested changes

2023-08-21 19:32 UTC, hawkw commented on linkerd.io/content/2-edge/tasks/upgrade.md
> +so. Note that this shouldn't cause any downtime in cross-cluster connections.
nit, take it or leave it: how about just:
```suggestion
so. This should not cause any downtime in cross-cluster connections.
```

2023-08-21 19:32 UTC, hawkw commented on linkerd.io/content/2-edge/tasks/upgrade.md
> +re-link your clusters. `linkerd multicluster check` will error out until you do
should this maybe say:
```suggestion
re-link your clusters after upgrading to stable-2.14.0. `linkerd multicluster check` will error out until you do
```

2023-08-21 19:32 UTC, hawkw commented on linkerd.io/content/2-edge/tasks/upgrade.md
> +re-link your clusters. `linkerd multicluster check` will error out until you do
are there consequences of not re-linking besides an error in `linkerd multicluster check`? If so, can we document those reasons it's necessary, as well? Or, if not, can we state that a failed `linkerd multicluster check` is the only consequence of not re-linking?

2023-08-21 20:26 UTC, alpeb commented on linkerd.io/content/2-edge/tasks/upgrade.md
> +re-link your clusters. `linkerd multicluster check` will error out until you do
If they don't re-link, the service mirror controllers won't acquire the new images with upgrades like the HA ability we added in this release, like explained above in the "Upgrading the multicluster extension" section. I'll try to reword this a little clearer.

2023-08-21 21:31 UTC, hawkw commented on linkerd.io/content/2-edge/tasks/upgrade.md
> +[above](#upgrading-the-multicluster-extension). Not doing immediately so won't
```suggestion
[above](#upgrading-the-multicluster-extension). Not doing so immediately won't
```

2023-08-21 21:32 UTC, hawkw commented on linkerd.io/content/2-edge/tasks/upgrade.md
> +check` will error out.
this is nitpicky, but i don't love the phrase "error out". how about
```suggestion
check` will not succeed until the clusters are re-linked.
```

take it or leave it.

2023-08-22 16:51 UTC, hawkw approved these changes
looks great!

2023-08-22 16:52 UTC, merged