Add troubleshooting section to pod-to-pod-multicluster for required metadata in secret
linkerd/website pull request #1705
Opened 2023-11-05 21:01 UTC by Majkel1999

Adding `Troubleshooting` section to the pod-to-pod-multicluster task, as the required metadata for secrets in control plane namespace is not documented.

References:
* https://github.com/linkerd/linkerd2/issues/11542
* https://github.com/linkerd/linkerd2/blob/ce950d17c60eab8c7c2a3e67c130241f96056ac2/controller/api/destination/watcher/cluster_store.go#L63C1-L67

2023-11-07 16:22 UTC, alpeb commented
The `linkerd multicluster link` command should be used to retrieve the Link resource and the other associated resources (including those Secrets) to have multicluster communication properly work. I understand it's not always possible to plug a call to this command in all deployment pipelines, but the manifests to use should still be sourced from this command which provides the ultimate source of truth. So I don't see why we need to single out specific metadata that is already provided, and that is required just like many other pieces of metadata in other linkerd resources.

2023-11-30 04:35 UTC, kflynn requested changes
@Majkel1999, thanks for digging into this! I left some comments about how I think this could be improved. 🙂

2023-11-30 04:35 UTC, kflynn commented on linkerd.io/content/2.14/tasks/pod-to-pod-multicluster.md
> +The second secret (in `linkerd` namespace) has a specific metadata requirements. Labels and annotations shown below are neccessary for the control plane, to be able to retrieve the remote cluster cre
@Majkel1999, to @alpeb's point, I think it's very important to say here that these Secrets are meant to be managed by the `linkerd multicluster link` command. I'm OK with providing more details, but I feel that the real core thing we need to make sure people understand is that this error generally means that they haven't properly used `linkerd multicluster link`. 🙂

2023-11-30 04:35 UTC, kflynn commented on linkerd.io/content/2.14/tasks/pod-to-pod-multicluster.md
> +2. `cluster-credentials-<remote-cluster-name>` residing in the LinkerD control-plane namespace -- usually `linkerd`.
"Linkerd" instead of "LinkerD". 🙂

2025-01-27 21:49 UTC, wmorgan commented
I'm going to close this as stale, but I do think the underlying problems here are valid, and should be addressed by some upcoming product work.

2025-01-27 21:49 UTC, closed without merging

2026-06-16 15:42 UTC, ritchellesap commented
Hi folks, I'm setting up linkerd multicluster in flat network mode and ran into this issue. I followed this [guide](https://linkerd.io/docs/tasks/pod-to-pod-multicluster/). I'm running on version `edge-26.4.2`.
Can confirm this bug also bit my setup. Adding the metadata labels and annotations was the fix for my linkerd-destination pod. Cheers!