Update traefik ingress docs
linkerd/website pull request #1855
Opened 2024-10-18 18:46 UTC by chicocvenancio

Fixes #1633

2024-10-21 17:48 UTC, kflynn requested changes
Thanks @chicocvenancio! There are a few tweaks that I'd like to see, but this looks way better than what we had before and I appreciate it! 🙂

2024-10-21 17:48 UTC, kflynn commented on linkerd.io/content/2.16/tasks/using-ingress.md
> +  - [Traefik with ingress mode](#traefik-ingress-mode)
Can you make clear even here that any version prior to 2.10 really must use ingress mode? 🙂

2024-10-21 17:48 UTC, kflynn commented on linkerd.io/content/2.16/tasks/using-ingress.md
> +Previous versions of Ttraefik needed to use [ingress mode](#ingress-mode),
```suggestion
Versions of Traefik prior to 2.10 must use [ingress mode](#ingress-mode),
```

2024-10-21 17:48 UTC, kflynn commented on linkerd.io/content/2.16/tasks/using-ingress.md
> +apiVersion: traefik.io/v1alpha1
What version of Traefik is required for this API group change?

2024-10-22 12:50 UTC, chicocvenancio commented on linkerd.io/content/2.16/tasks/using-ingress.md
> +apiVersion: traefik.io/v1alpha1
Version 2.10 as well. `traefik.containo.us` is dropped in v3.

2024-10-22 14:51 UTC, kflynn requested changes
Thanks @chicocvenancio! This looks great save for one small typo.

2024-10-22 14:51 UTC, kflynn commented on linkerd.io/content/2.16/tasks/using-ingress.md
> +The YAML bellow exemplifies an IngressRoute for `emojivoto` application.
```suggestion
The YAML below exemplifies an IngressRoute for `emojivoto` application.
```

2024-10-22 14:53 UTC, kflynn commented
Also, it would be lovely if you could add the [DCO](https://developercertificate.org/) signature to your commits (or just confirm here that you're OK with the DCO).

2024-10-22 18:58 UTC, chicocvenancio commented on linkerd.io/content/2.16/tasks/using-ingress.md
> +apiVersion: traefik.io/v1alpha1
I left new api group for versions 2.10 and up example but kept old group for the legacy example.

2024-10-22 19:00 UTC, chicocvenancio commented
Rebased to sign off all commits and fixed the typo.

2024-10-22 19:03 UTC, kflynn approved these changes
Many thanks!! 🙂

2024-10-22 21:54 UTC, kflynn commented
Looks like this needs to have `main` merged before we can land it? Sorry for the extra hassle!

2024-10-23 14:38 UTC, merged

2024-10-23 14:38 UTC, kflynn commented
Thanks for sticking with this one, @chicocvenancio! 🙂