Add federated services docs
linkerd/website pull request #1874
Opened 2024-11-08 00:25 UTC by adleong

2024-11-08 17:12 UTC, wmorgan commented on linkerd.io/content/2-edge/reference/multicluster.md
> +the `store-web-federated` federated service will be load balananced over all
```suggestion
the `store-web-federated` federated service will be load balanced over all
```

2024-11-08 17:12 UTC, wmorgan commented on linkerd.io/content/2-edge/reference/multicluster.md
> +deployed to multiple clusters to be joined into a single federated service.
Maybe single "logical" service to avoid a recursive definition?

2024-11-08 17:13 UTC, wmorgan commented on linkerd.io/content/2-edge/reference/multicluster.md
> +Since Linkerd's *destination servce* uses "remote-discovery" to discovery the
```suggestion
Since Linkerd's *destination service* uses "remote-discovery" to discover the
```

2024-11-08 17:18 UTC, wmorgan commented on linkerd.io/content/2-edge/tasks/federated-services.md
> +title: Multi-Cluster Federated Services
We haven't always stuck to this so it is currently inconsistent, but could you please make this a present participle phrase, e.g. "Using multi-cluster federated services" or "Federating your services" or something like that.

2024-11-08 17:25 UTC, wmorgan commented on linkerd.io/content/2-edge/reference/multicluster.md
> +deployed to multiple clusters to be joined into a single federated service.
I think I saw "union" elsewhere, that might be an option here too.

2024-11-22 19:30 UTC, alpeb commented on linkerd.io/content/2-edge/reference/multicluster.md
> +replicas of all services name `store-web` in all linked clusters.
```suggestion
replicas of all services named `store-web` in all linked clusters.
```

2024-11-22 19:30 UTC, alpeb commented on linkerd.io/content/2-edge/tasks/federated-services.md
> +clusters. The allows the client to be cluster agnostic, balance traffic across
```suggestion
clusters. This allows the client to be cluster agnostic, balance traffic across
```

2024-11-22 19:30 UTC, alpeb commented on linkerd.io/content/2-edge/tasks/federated-services.md
> +## Step 5: Send some traffic!
```suggestion
## Step 6: Send some traffic!
```

2024-11-22 19:31 UTC, alpeb commented on linkerd.io/content/2-edge/tasks/federated-services.md
> +        image: appropriate/curl
I assume this was a placeholder?
```suggestion
        image: curlimages/curl
```

2024-11-25 23:01 UTC, adleong commented on linkerd.io/content/2-edge/tasks/federated-services.md
> +        image: appropriate/curl
nope, https://github.com/appropriate/docker-curl

2024-11-26 18:28 UTC, kflynn requested changes
Some minor tweaks suggested but this looks excellent, kudos! 🙂

2024-11-26 18:28 UTC, kflynn commented on linkerd.io/content/2-edge/features/multicluster.md
> +is most appropriate. See the
```suggestion
These modes can be combined, with each specific services selecting the mode that
is most appropriate for that service. See the
```

2024-11-26 18:28 UTC, kflynn commented on linkerd.io/content/2-edge/reference/multicluster.md
>    cluster be reachable by pods on the source cluster.
I realize you didn't change this in this PR, but can we swap these two modes so the order of the descriptions are heirarchical, flat, federated to match the "three modes" text above?

2024-11-26 18:28 UTC, kflynn commented on linkerd.io/content/2-edge/reference/multicluster.md
> +modes: hierarchical (using an gateway), flat (without a gateway), and federated.
```suggestion
modes: hierarchical (using a gateway), flat (without a gateway), and federated.
```

2024-11-26 18:28 UTC, kflynn commented on linkerd.io/content/2-edge/reference/multicluster.md
> +deployed to multiple clusters to be joined into a single union service.
```suggestion
deployed to multiple clusters to be joined into a single unified service.
```

maybe?

2024-11-26 18:28 UTC, kflynn commented on linkerd.io/content/2-edge/tasks/federated-services.md
> +not through a gateway. Therefore, federated services have the same requirements
```suggestion
Federated services send traffic directly to the pods of the member services
rather than using a gateway. Therefore, federated services have the same requirements
```

2024-11-26 18:28 UTC, kflynn commented on linkerd.io/content/2-edge/tasks/federated-services.md
> +  with `kubectl`, so don't feel like you need to keep it all named this way
```suggestion
  with `kubectl`, so don't feel like you need to keep them all named this way
```

2024-11-26 18:28 UTC, kflynn commented on linkerd.io/content/2-edge/tasks/federated-services.md
> +We use the `linkerd multilcuster link` command to link the `east` and `north`
```suggestion
We use the `linkerd multicluster link` command to link the `east` and `north`
```

2024-12-03 22:38 UTC, olix0r commented on linkerd.io/content/2-edge/tasks/federated-services.md
> +        image: appropriate/curl
FWIW, It would be better to point at an actively maintained image: https://hub.docker.com/r/curlimages/curl

2024-12-04 04:37 UTC, kflynn approved these changes
This looks great, though I've logged a couple of nits. Thanks!! 🙂

2024-12-04 04:37 UTC, kflynn commented on linkerd.io/content/2-edge/features/multicluster.md
>  they are used when a workloads needs a stable network identifier or to
```suggestion
assigned to it. In general, headless services *should not have an IP address*;
they are used when a workload needs a stable network identifier or to
```

(I know the second line here isn't something you changed, I just noticed it.)

2024-12-04 04:37 UTC, kflynn commented on linkerd.io/content/2-edge/tasks/federated-services.md
> +        image: appropriate/curl
I tend to agree with Oliver htere -- `appropriate/docker-curl`'s last change was almost before Kubernetes. 🙂

2024-12-04 17:55 UTC, merged