Add egress documentation
linkerd/website pull request #1884
Opened 2024-11-27 13:10 UTC by zaharidichev

Signed-off-by: Zahari Dichev <zaharidichev@gmail.com>

2024-11-30 01:33 UTC, kflynn requested changes
I've suggested some wording changes but this is really helpful, thanks much!! 🙂

2024-12-04 04:27 UTC, kflynn requested changes
Four more tiny things -- let me know if you'd rather I just merge these! Many thanks. 🙂

2024-12-04 04:27 UTC, kflynn commented on linkerd.io/content/2-edge/reference/egress-network.md
> +controller by creating `EgressNetwork` resources, which describe the properties
```suggestion
controlled by creating `EgressNetwork` resources, which describe the properties
```

2024-12-04 04:27 UTC, kflynn commented on linkerd.io/content/2-edge/tasks/managing-egress-traffic.md
> +Notice that these raw metrics allow to quickly identify egress traffic targeted
```suggestion
Notice that these raw metrics allow you to quickly identify egress traffic targeted
```

2024-12-04 04:27 UTC, kflynn commented on linkerd.io/content/2-edge/tasks/managing-egress-traffic.md
> +name of the route is not `http-egress-deny`. Furthermore, the `http_status` is
```suggestion
name of the route is now `http-egress-deny`. Furthermore, the `http_status` is
```

2024-12-04 04:27 UTC, kflynn commented on linkerd.io/content/2-edge/tasks/managing-egress-traffic.md
> +To begin with, lets create our internal service to which traffic should be
```suggestion
To begin with, let's create our internal service to which traffic should be
```

2024-12-04 12:04 UTC, wmorgan commented on linkerd.io/content/2-edge/features/egress.md
> +Related content:
I would add another bit here:

Linkerd's egress control is implemented in the sidecar proxy itself, not in a separate gateway.

{{< warning >}}
Like all service meshes, Linkerd cannot, by itself, provide a strong security guarantees about egress traffic from pods. Malicious applications can bypass the Linkerd sidecar. Fully restricting egress traffic in the presence of arbitrary applications thus typically requires a more comprehensive approach e.g. with a dedicated, meshed egress proxy combined with CNI-level configuration.
{{< /warning }}

Something like that.

2024-12-04 15:43 UTC, kflynn approved these changes
Thanks! Looks good to me but let's see if @wmorgan can chime in quickly. 🙂

2024-12-04 16:05 UTC, wmorgan commented on linkerd.io/content/2-edge/features/egress.md
> +No service mesh can provide a strong security guarantee about egress traffic
Just fine tuning: Even a meshed application can bypass its proxy in certain conditions, so I would generalize the first statement (cf. https://blog.howardjohn.info/posts/bypass-egress/). I would also probably generalize the last sentence a bit since I am not convinced that just adding CNI config on top of the existing egress setup is by itself sufficient.

2024-12-04 16:26 UTC, merged