Proxy log-level: admin-API linked in ref. & task generalised
linkerd/website pull request #890
Opened 2021-01-11 15:39 UTC by Dominik-K

Setting the proxy log-level on a running proxy wasn't documented in the appropriate reference.

2021-01-13 18:16 UTC, cpretzer commented on linkerd.io/content/2/tasks/modifying-proxy-log-level.md
> +`/proxy-log-level` endpoint on the admin-API.
Nit: I think you can refer to it as admin API or admin endpoint. I've not seen `admin-API` used elsewhere and it would be good to keep it consistent

2021-01-13 18:16 UTC, cpretzer commented on linkerd.io/content/2/tasks/modifying-proxy-log-level.md
> +kubectl port-forward ${POD:?} linkerd-admin
This example uses env var notation `${POD:?}`, which is better than the random pod name, and it would be good to add a note about setting $POD in the previous paragraph.

Is there an advantage to using `linkerd-admin` instead of `4191`?

2021-01-19 16:57 UTC, Dominik-K commented on linkerd.io/content/2/tasks/modifying-proxy-log-level.md
> +`/proxy-log-level` endpoint on the admin-API.
Ok. I used now "admin-port" instead. It's used at least [sometimes in documentation](https://github.com/linkerd/website/search?q=%22admin+port%22), especially the same name in the [proxy configuration](https://linkerd.io/2/reference/proxy-configuration/).

"admin API" occurs [0 times](https://github.com/linkerd/website/search?q=%22admin+API%22) and "admin endpoint" would double "endpoint" in here.

2021-01-19 17:02 UTC, Dominik-K commented on linkerd.io/content/2/tasks/modifying-proxy-log-level.md
> +kubectl port-forward ${POD:?} linkerd-admin
> add a note about setting $POD in the previous paragraph.

Done.

> Is there an advantage to using linkerd-admin instead of 4191?

Sure. It's way easier to remember instead the number. I prefer to use named-ports instead numbers. `kubectl` then prints the port-number to use in further calls, e.g. at `curl`.

2021-01-19 21:44 UTC, cpretzer requested changes
@Dominik-K there are some lint checks failing, would you mind addressing those? then we can get this merged: https://github.com/linkerd/website/pull/890/checks?check_run_id=1729319549

2021-01-23 10:30 UTC, Dominik-K commented
@cpretzer Now the linter is happy. 
It's somehow annoying and confusing that the updates from Forestry.io introduce linter-issues directly into `master` (and then into contributors PRs, too). Latest one [here](https://github.com/linkerd/website/pull/890/checks?check_run_id=1749907732).

2021-01-26 19:08 UTC, cpretzer approved these changes
LGTM

2021-01-26 19:09 UTC, merged

2021-01-26 19:09 UTC, cpretzer commented
@Dominik-K you're right about the forestry updates being troublesome. I'm looking into how we can fix this and keep the integrity of the docs